/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing ColorResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ColorResultTests
    {
        // TODO uncomment below to declare an instance variable for ColorResult
        //private ColorResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ColorResult
            //instance = new ColorResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ColorResult
        /// </summary>
        [Test]
        public void ColorResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ColorResult
            //Assert.IsInstanceOfType<ColorResult> (instance, "variable 'instance' is a ColorResult");
        }


        /// <summary>
        /// Test the property 'R'
        /// </summary>
        [Test]
        public void RTest()
        {
            // TODO unit test for the property 'R'
        }
        /// <summary>
        /// Test the property 'G'
        /// </summary>
        [Test]
        public void GTest()
        {
            // TODO unit test for the property 'G'
        }
        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Test]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }

    }

}
