/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing CreateHandwritingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateHandwritingRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateHandwritingRequest
        //private CreateHandwritingRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateHandwritingRequest
            //instance = new CreateHandwritingRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateHandwritingRequest
        /// </summary>
        [Test]
        public void CreateHandwritingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateHandwritingRequest
            //Assert.IsInstanceOfType<CreateHandwritingRequest> (instance, "variable 'instance' is a CreateHandwritingRequest");
        }


        /// <summary>
        /// Test the property 'TextInput'
        /// </summary>
        [Test]
        public void TextInputTest()
        {
            // TODO unit test for the property 'TextInput'
        }
        /// <summary>
        /// Test the property 'TargetWidth'
        /// </summary>
        [Test]
        public void TargetWidthTest()
        {
            // TODO unit test for the property 'TargetWidth'
        }
        /// <summary>
        /// Test the property 'StrokeWidth'
        /// </summary>
        [Test]
        public void StrokeWidthTest()
        {
            // TODO unit test for the property 'StrokeWidth'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

    }

}
