/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing DetectedLicensePlate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetectedLicensePlateTests
    {
        // TODO uncomment below to declare an instance variable for DetectedLicensePlate
        //private DetectedLicensePlate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetectedLicensePlate
            //instance = new DetectedLicensePlate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetectedLicensePlate
        /// </summary>
        [Test]
        public void DetectedLicensePlateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetectedLicensePlate
            //Assert.IsInstanceOfType<DetectedLicensePlate> (instance, "variable 'instance' is a DetectedLicensePlate");
        }


        /// <summary>
        /// Test the property 'LicensePlateTextBestMatch'
        /// </summary>
        [Test]
        public void LicensePlateTextBestMatchTest()
        {
            // TODO unit test for the property 'LicensePlateTextBestMatch'
        }
        /// <summary>
        /// Test the property 'LicensePlateTextRunnerUp'
        /// </summary>
        [Test]
        public void LicensePlateTextRunnerUpTest()
        {
            // TODO unit test for the property 'LicensePlateTextRunnerUp'
        }
        /// <summary>
        /// Test the property 'LocationX'
        /// </summary>
        [Test]
        public void LocationXTest()
        {
            // TODO unit test for the property 'LocationX'
        }
        /// <summary>
        /// Test the property 'LocationY'
        /// </summary>
        [Test]
        public void LocationYTest()
        {
            // TODO unit test for the property 'LocationY'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'LicensePlateRecognitionConfidenceLevel'
        /// </summary>
        [Test]
        public void LicensePlateRecognitionConfidenceLevelTest()
        {
            // TODO unit test for the property 'LicensePlateRecognitionConfidenceLevel'
        }

    }

}
