/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing DrawTextRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DrawTextRequestTests
    {
        // TODO uncomment below to declare an instance variable for DrawTextRequest
        //private DrawTextRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DrawTextRequest
            //instance = new DrawTextRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DrawTextRequest
        /// </summary>
        [Test]
        public void DrawTextRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DrawTextRequest
            //Assert.IsInstanceOfType<DrawTextRequest> (instance, "variable 'instance' is a DrawTextRequest");
        }


        /// <summary>
        /// Test the property 'BaseImageBytes'
        /// </summary>
        [Test]
        public void BaseImageBytesTest()
        {
            // TODO unit test for the property 'BaseImageBytes'
        }
        /// <summary>
        /// Test the property 'BaseImageUrl'
        /// </summary>
        [Test]
        public void BaseImageUrlTest()
        {
            // TODO unit test for the property 'BaseImageUrl'
        }
        /// <summary>
        /// Test the property 'TextToDraw'
        /// </summary>
        [Test]
        public void TextToDrawTest()
        {
            // TODO unit test for the property 'TextToDraw'
        }

    }

}
