/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing DrawRectangleInstance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DrawRectangleInstanceTests
    {
        // TODO uncomment below to declare an instance variable for DrawRectangleInstance
        //private DrawRectangleInstance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DrawRectangleInstance
            //instance = new DrawRectangleInstance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DrawRectangleInstance
        /// </summary>
        [Test]
        public void DrawRectangleInstanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DrawRectangleInstance
            //Assert.IsInstanceOfType<DrawRectangleInstance> (instance, "variable 'instance' is a DrawRectangleInstance");
        }


        /// <summary>
        /// Test the property 'BorderColor'
        /// </summary>
        [Test]
        public void BorderColorTest()
        {
            // TODO unit test for the property 'BorderColor'
        }
        /// <summary>
        /// Test the property 'BorderWidth'
        /// </summary>
        [Test]
        public void BorderWidthTest()
        {
            // TODO unit test for the property 'BorderWidth'
        }
        /// <summary>
        /// Test the property 'FillColor'
        /// </summary>
        [Test]
        public void FillColorTest()
        {
            // TODO unit test for the property 'FillColor'
        }
        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Test]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }
        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Test]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

    }

}
