/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing FaceWithLandmarks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FaceWithLandmarksTests
    {
        // TODO uncomment below to declare an instance variable for FaceWithLandmarks
        //private FaceWithLandmarks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FaceWithLandmarks
            //instance = new FaceWithLandmarks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FaceWithLandmarks
        /// </summary>
        [Test]
        public void FaceWithLandmarksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FaceWithLandmarks
            //Assert.IsInstanceOfType<FaceWithLandmarks> (instance, "variable 'instance' is a FaceWithLandmarks");
        }


        /// <summary>
        /// Test the property 'LeftX'
        /// </summary>
        [Test]
        public void LeftXTest()
        {
            // TODO unit test for the property 'LeftX'
        }
        /// <summary>
        /// Test the property 'TopY'
        /// </summary>
        [Test]
        public void TopYTest()
        {
            // TODO unit test for the property 'TopY'
        }
        /// <summary>
        /// Test the property 'RightX'
        /// </summary>
        [Test]
        public void RightXTest()
        {
            // TODO unit test for the property 'RightX'
        }
        /// <summary>
        /// Test the property 'BottomY'
        /// </summary>
        [Test]
        public void BottomYTest()
        {
            // TODO unit test for the property 'BottomY'
        }
        /// <summary>
        /// Test the property 'LeftEyebrow'
        /// </summary>
        [Test]
        public void LeftEyebrowTest()
        {
            // TODO unit test for the property 'LeftEyebrow'
        }
        /// <summary>
        /// Test the property 'RightEyebrow'
        /// </summary>
        [Test]
        public void RightEyebrowTest()
        {
            // TODO unit test for the property 'RightEyebrow'
        }
        /// <summary>
        /// Test the property 'LeftEye'
        /// </summary>
        [Test]
        public void LeftEyeTest()
        {
            // TODO unit test for the property 'LeftEye'
        }
        /// <summary>
        /// Test the property 'RightEye'
        /// </summary>
        [Test]
        public void RightEyeTest()
        {
            // TODO unit test for the property 'RightEye'
        }
        /// <summary>
        /// Test the property 'BottomAndSidesOfFace'
        /// </summary>
        [Test]
        public void BottomAndSidesOfFaceTest()
        {
            // TODO unit test for the property 'BottomAndSidesOfFace'
        }
        /// <summary>
        /// Test the property 'NoseBridge'
        /// </summary>
        [Test]
        public void NoseBridgeTest()
        {
            // TODO unit test for the property 'NoseBridge'
        }
        /// <summary>
        /// Test the property 'NoseBottom'
        /// </summary>
        [Test]
        public void NoseBottomTest()
        {
            // TODO unit test for the property 'NoseBottom'
        }
        /// <summary>
        /// Test the property 'LipsInnerOutline'
        /// </summary>
        [Test]
        public void LipsInnerOutlineTest()
        {
            // TODO unit test for the property 'LipsInnerOutline'
        }
        /// <summary>
        /// Test the property 'LipsOuterOutline'
        /// </summary>
        [Test]
        public void LipsOuterOutlineTest()
        {
            // TODO unit test for the property 'LipsOuterOutline'
        }

    }

}
