/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing GenderDetectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GenderDetectionResultTests
    {
        // TODO uncomment below to declare an instance variable for GenderDetectionResult
        //private GenderDetectionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenderDetectionResult
            //instance = new GenderDetectionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenderDetectionResult
        /// </summary>
        [Test]
        public void GenderDetectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GenderDetectionResult
            //Assert.IsInstanceOfType<GenderDetectionResult> (instance, "variable 'instance' is a GenderDetectionResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'PersonWithGender'
        /// </summary>
        [Test]
        public void PersonWithGenderTest()
        {
            // TODO unit test for the property 'PersonWithGender'
        }
        /// <summary>
        /// Test the property 'PeopleIdentified'
        /// </summary>
        [Test]
        public void PeopleIdentifiedTest()
        {
            // TODO unit test for the property 'PeopleIdentified'
        }

    }

}
