/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing ImageSimilarityHashDistanceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ImageSimilarityHashDistanceRequestTests
    {
        // TODO uncomment below to declare an instance variable for ImageSimilarityHashDistanceRequest
        //private ImageSimilarityHashDistanceRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ImageSimilarityHashDistanceRequest
            //instance = new ImageSimilarityHashDistanceRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ImageSimilarityHashDistanceRequest
        /// </summary>
        [Test]
        public void ImageSimilarityHashDistanceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ImageSimilarityHashDistanceRequest
            //Assert.IsInstanceOfType<ImageSimilarityHashDistanceRequest> (instance, "variable 'instance' is a ImageSimilarityHashDistanceRequest");
        }


        /// <summary>
        /// Test the property 'ImageHash1'
        /// </summary>
        [Test]
        public void ImageHash1Test()
        {
            // TODO unit test for the property 'ImageHash1'
        }
        /// <summary>
        /// Test the property 'ImageHash2'
        /// </summary>
        [Test]
        public void ImageHash2Test()
        {
            // TODO unit test for the property 'ImageHash2'
        }

    }

}
