/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing ObjectDetectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ObjectDetectionResultTests
    {
        // TODO uncomment below to declare an instance variable for ObjectDetectionResult
        //private ObjectDetectionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ObjectDetectionResult
            //instance = new ObjectDetectionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObjectDetectionResult
        /// </summary>
        [Test]
        public void ObjectDetectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ObjectDetectionResult
            //Assert.IsInstanceOfType<ObjectDetectionResult> (instance, "variable 'instance' is a ObjectDetectionResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'Objects'
        /// </summary>
        [Test]
        public void ObjectsTest()
        {
            // TODO unit test for the property 'Objects'
        }
        /// <summary>
        /// Test the property 'ObjectCount'
        /// </summary>
        [Test]
        public void ObjectCountTest()
        {
            // TODO unit test for the property 'ObjectCount'
        }

    }

}
