/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing PersonWithGender
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PersonWithGenderTests
    {
        // TODO uncomment below to declare an instance variable for PersonWithGender
        //private PersonWithGender instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PersonWithGender
            //instance = new PersonWithGender();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PersonWithGender
        /// </summary>
        [Test]
        public void PersonWithGenderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PersonWithGender
            //Assert.IsInstanceOfType<PersonWithGender> (instance, "variable 'instance' is a PersonWithGender");
        }


        /// <summary>
        /// Test the property 'FaceLocation'
        /// </summary>
        [Test]
        public void FaceLocationTest()
        {
            // TODO unit test for the property 'FaceLocation'
        }
        /// <summary>
        /// Test the property 'GenderClassificationConfidence'
        /// </summary>
        [Test]
        public void GenderClassificationConfidenceTest()
        {
            // TODO unit test for the property 'GenderClassificationConfidence'
        }
        /// <summary>
        /// Test the property 'GenderClass'
        /// </summary>
        [Test]
        public void GenderClassTest()
        {
            // TODO unit test for the property 'GenderClass'
        }

    }

}
