/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;
using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing PersonWithAge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PersonWithAgeTests
    {
        // TODO uncomment below to declare an instance variable for PersonWithAge
        //private PersonWithAge instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PersonWithAge
            //instance = new PersonWithAge();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PersonWithAge
        /// </summary>
        [Test]
        public void PersonWithAgeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PersonWithAge
            //Assert.IsInstanceOfType<PersonWithAge> (instance, "variable 'instance' is a PersonWithAge");
        }


        /// <summary>
        /// Test the property 'FaceLocation'
        /// </summary>
        [Test]
        public void FaceLocationTest()
        {
            // TODO unit test for the property 'FaceLocation'
        }
        /// <summary>
        /// Test the property 'AgeClassificationConfidence'
        /// </summary>
        [Test]
        public void AgeClassificationConfidenceTest()
        {
            // TODO unit test for the property 'AgeClassificationConfidence'
        }
        /// <summary>
        /// Test the property 'AgeClass'
        /// </summary>
        [Test]
        public void AgeClassTest()
        {
            // TODO unit test for the property 'AgeClass'
        }
        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Test]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }
        /// <summary>
        /// Test the property 'GenderClassification'
        /// </summary>
        [Test]
        public void GenderClassificationTest()
        {
            // TODO unit test for the property 'GenderClassification'
        }
        /// <summary>
        /// Test the property 'GenderFemaleConfidence'
        /// </summary>
        [Test]
        public void GenderFemaleConfidenceTest()
        {
            // TODO unit test for the property 'GenderFemaleConfidence'
        }
        /// <summary>
        /// Test the property 'GenderMaleConfidence'
        /// </summary>
        [Test]
        public void GenderMaleConfidenceTest()
        {
            // TODO unit test for the property 'GenderMaleConfidence'
        }

    }

}
