/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.ImageRecognition.Client;
using Cloudmersive.APIClient.NET.ImageRecognition.Api;
using Cloudmersive.APIClient.NET.ImageRecognition.Model;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Test
{
    /// <summary>
    ///  Class for testing NsfwApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NsfwApiTests
    {
        private NsfwApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NsfwApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NsfwApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NsfwApi
            //Assert.IsInstanceOfType(typeof(NsfwApi), instance, "instance is a NsfwApi");
        }

        
        /// <summary>
        /// Test NsfwClassify
        /// </summary>
        [Test]
        public void NsfwClassifyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream imageFile = null;
            //var response = instance.NsfwClassify(imageFile);
            //Assert.IsInstanceOf<NsfwResult> (response, "response is NsfwResult");
        }
        
        /// <summary>
        /// Test NsfwClassifyAdvanced
        /// </summary>
        [Test]
        public void NsfwClassifyAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream imageFile = null;
            //var response = instance.NsfwClassifyAdvanced(imageFile);
            //Assert.IsInstanceOf<NsfwAdvancedResult> (response, "response is NsfwAdvancedResult");
        }
        
        /// <summary>
        /// Test NsfwClassifyDocument
        /// </summary>
        [Test]
        public void NsfwClassifyDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream imageFile = null;
            //var response = instance.NsfwClassifyDocument(imageFile);
            //Assert.IsInstanceOf<NsfwResult> (response, "response is NsfwResult");
        }
        
        /// <summary>
        /// Test NsfwClassifyVideo
        /// </summary>
        [Test]
        public void NsfwClassifyVideoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream videoFile = null;
            //var response = instance.NsfwClassifyVideo(videoFile);
            //Assert.IsInstanceOf<NsfwResult> (response, "response is NsfwResult");
        }
        
    }

}
