/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.ImageRecognition.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Model
{
    /// <summary>
    /// Result of a find symbol operation on an input image
    /// </summary>
    [DataContract]
    public partial class FindSymbolResult :  IEquatable<FindSymbolResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindSymbolResult" /> class.
        /// </summary>
        /// <param name="successful">True if successful, false otherwise.</param>
        /// <param name="matchScore">Score between 0.0 and 1.0 that measures how closely the symbol matched; scores above 0.2 are good.</param>
        /// <param name="xLeft">X location of the left edge of the found location in pixels.</param>
        /// <param name="yTop">Y location of the top edge of the found location in pixels.</param>
        /// <param name="width">Width of the found location in pixels.</param>
        /// <param name="height">Height of the found location in pixels.</param>
        public FindSymbolResult(bool? successful = default(bool?), double? matchScore = default(double?), int? xLeft = default(int?), int? yTop = default(int?), int? width = default(int?), int? height = default(int?))
        {
            this.Successful = successful;
            this.MatchScore = matchScore;
            this.XLeft = xLeft;
            this.YTop = yTop;
            this.Width = width;
            this.Height = height;
        }
        
        /// <summary>
        /// True if successful, false otherwise
        /// </summary>
        /// <value>True if successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Score between 0.0 and 1.0 that measures how closely the symbol matched; scores above 0.2 are good
        /// </summary>
        /// <value>Score between 0.0 and 1.0 that measures how closely the symbol matched; scores above 0.2 are good</value>
        [DataMember(Name="MatchScore", EmitDefaultValue=false)]
        public double? MatchScore { get; set; }

        /// <summary>
        /// X location of the left edge of the found location in pixels
        /// </summary>
        /// <value>X location of the left edge of the found location in pixels</value>
        [DataMember(Name="XLeft", EmitDefaultValue=false)]
        public int? XLeft { get; set; }

        /// <summary>
        /// Y location of the top edge of the found location in pixels
        /// </summary>
        /// <value>Y location of the top edge of the found location in pixels</value>
        [DataMember(Name="YTop", EmitDefaultValue=false)]
        public int? YTop { get; set; }

        /// <summary>
        /// Width of the found location in pixels
        /// </summary>
        /// <value>Width of the found location in pixels</value>
        [DataMember(Name="Width", EmitDefaultValue=false)]
        public int? Width { get; set; }

        /// <summary>
        /// Height of the found location in pixels
        /// </summary>
        /// <value>Height of the found location in pixels</value>
        [DataMember(Name="Height", EmitDefaultValue=false)]
        public int? Height { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FindSymbolResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  MatchScore: ").Append(MatchScore).Append("\n");
            sb.Append("  XLeft: ").Append(XLeft).Append("\n");
            sb.Append("  YTop: ").Append(YTop).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FindSymbolResult);
        }

        /// <summary>
        /// Returns true if FindSymbolResult instances are equal
        /// </summary>
        /// <param name="input">Instance of FindSymbolResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FindSymbolResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.MatchScore == input.MatchScore ||
                    (this.MatchScore != null &&
                    this.MatchScore.Equals(input.MatchScore))
                ) && 
                (
                    this.XLeft == input.XLeft ||
                    (this.XLeft != null &&
                    this.XLeft.Equals(input.XLeft))
                ) && 
                (
                    this.YTop == input.YTop ||
                    (this.YTop != null &&
                    this.YTop.Equals(input.YTop))
                ) && 
                (
                    this.Width == input.Width ||
                    (this.Width != null &&
                    this.Width.Equals(input.Width))
                ) && 
                (
                    this.Height == input.Height ||
                    (this.Height != null &&
                    this.Height.Equals(input.Height))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.MatchScore != null)
                    hashCode = hashCode * 59 + this.MatchScore.GetHashCode();
                if (this.XLeft != null)
                    hashCode = hashCode * 59 + this.XLeft.GetHashCode();
                if (this.YTop != null)
                    hashCode = hashCode * 59 + this.YTop.GetHashCode();
                if (this.Width != null)
                    hashCode = hashCode * 59 + this.Width.GetHashCode();
                if (this.Height != null)
                    hashCode = hashCode * 59 + this.Height.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
