/* 
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.ImageRecognition.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.ImageRecognition.Model
{
    /// <summary>
    /// Result of detecting vehicle license plates in an image
    /// </summary>
    [DataContract]
    public partial class VehicleLicensePlateDetectionResult :  IEquatable<VehicleLicensePlateDetectionResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleLicensePlateDetectionResult" /> class.
        /// </summary>
        /// <param name="successful">Was the image processed successfully?.</param>
        /// <param name="detectedLicensePlates">License plates found in the image.</param>
        /// <param name="detectedLicensePlateCount">The number of license plates detected in the image.</param>
        public VehicleLicensePlateDetectionResult(bool? successful = default(bool?), List<DetectedLicensePlate> detectedLicensePlates = default(List<DetectedLicensePlate>), int? detectedLicensePlateCount = default(int?))
        {
            this.Successful = successful;
            this.DetectedLicensePlates = detectedLicensePlates;
            this.DetectedLicensePlateCount = detectedLicensePlateCount;
        }
        
        /// <summary>
        /// Was the image processed successfully?
        /// </summary>
        /// <value>Was the image processed successfully?</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// License plates found in the image
        /// </summary>
        /// <value>License plates found in the image</value>
        [DataMember(Name="DetectedLicensePlates", EmitDefaultValue=false)]
        public List<DetectedLicensePlate> DetectedLicensePlates { get; set; }

        /// <summary>
        /// The number of license plates detected in the image
        /// </summary>
        /// <value>The number of license plates detected in the image</value>
        [DataMember(Name="DetectedLicensePlateCount", EmitDefaultValue=false)]
        public int? DetectedLicensePlateCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VehicleLicensePlateDetectionResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  DetectedLicensePlates: ").Append(DetectedLicensePlates).Append("\n");
            sb.Append("  DetectedLicensePlateCount: ").Append(DetectedLicensePlateCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VehicleLicensePlateDetectionResult);
        }

        /// <summary>
        /// Returns true if VehicleLicensePlateDetectionResult instances are equal
        /// </summary>
        /// <param name="input">Instance of VehicleLicensePlateDetectionResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VehicleLicensePlateDetectionResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.DetectedLicensePlates == input.DetectedLicensePlates ||
                    this.DetectedLicensePlates != null &&
                    this.DetectedLicensePlates.SequenceEqual(input.DetectedLicensePlates)
                ) && 
                (
                    this.DetectedLicensePlateCount == input.DetectedLicensePlateCount ||
                    (this.DetectedLicensePlateCount != null &&
                    this.DetectedLicensePlateCount.Equals(input.DetectedLicensePlateCount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.DetectedLicensePlates != null)
                    hashCode = hashCode * 59 + this.DetectedLicensePlates.GetHashCode();
                if (this.DetectedLicensePlateCount != null)
                    hashCode = hashCode * 59 + this.DetectedLicensePlateCount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
